name: Moto GPS Build

on:
  push:
    branches: [ main, master ] # Se activa al subir cambios a estas ramas

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.x'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        env:
          # Aquí inyectamos el secreto de GitHub a la variable de entorno que lee Gradle
          MAPBOX_DOWNLOADS_TOKEN: ${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}
        run: flutter build apk --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MotoGPS-Release-APK
          path: build/app/outputs/flutter-apk/app-release.apk
